### ISSUE TITLE
Tambahkan Profil Sonny Lazuardi

### ISSUE THREAD

**Issue by rizafahmi** [rizafahmi/awesome-speakers-id#17]
https://twitter.com/sonnylazuardi

**Comment by mblonyox** [comment]
Wah saya g tahu profil beliau mas. Kenalannya di mana?

**Comment by rizafahmi** [comment]
Itu diatas ada twitternya

**Comment by puterakahfi** [comment]
@mblonyox , bisa cek profilnya mas sonnylazuardi di sini  :)
https://puterakahfi.github.io/jsid/

**Comment by balbaal** [comment]
done !!, wait for approve PR mas @rizafahmi
