### ISSUE TITLE
Tambahkan Profil Sidiq Permana (GDE)

### ISSUE THREAD

**Issue by rizafahmi** [rizafahmi/awesome-speakers-id#4]
https://developers-dot-devsite-v2-prod.appspot.com/community/experts/directory/profile/profile-sidiq_permana

https://twitter.com/@nouvrizky10

**Comment by IhwanID** [comment]
Hi Mr @rizafahmi i add PR for this. 
https://github.com/rizafahmi/awesome-speakers-id/pull/5

**Comment by rizafahmi** [comment]
Nice!
