### ISSUE TITLE
ganti link twitter to linkedin or github

### ISSUE THREAD

**Issue by khannedy** [rizafahmi/awesome-speakers-id#56]
as tech people, rekomendasi saya, yang di cantumin itu link ke linkedin atau github, dibanding sosial media

**Comment by hendisantika** [comment]
Saya setuju sekali sama om @khannedy di atas.

**Comment by rizafahmi** [comment]
Tambahkan github setuju. Kalo linkedin kurang setuju. Developer nongkrongnya di Twitter soalnya, hehehe... Kalau berkenan mohon sekalian PR ya, terimakasih :)
