### ISSUE TITLE
Tambahkan Profil Imre Nagi (GDE)

### ISSUE THREAD

**Issue by rizafahmi** [rizafahmi/awesome-speakers-id#6]
https://twitter.com/imrenagi

**Comment by imrenagi** [comment]
mantep juga nih

**Comment by rizafahmi** [comment]
Wah belum ada yang ambil :D

**Comment by imrenagi** [comment]
pengen ngambil tapi nanti dikira ngaku2 awesome :p . semalem aja dibilang ngaku2 GDE sama @girikuncoro haha

**Comment by rizafahmi** [comment]
Hahaha.. Minta tolong @hellowin aja 😁

**Comment by mblonyox** [comment]
Ini rulesnya gak boleh klaim diri sendiri ya?

**Comment by rizafahmi** [comment]
Boleh aja @mblonyox

**Comment by puterakahfi** [comment]
cuman kalo claim sendiri kayaknya kurang greget mas @mblonyox . :)
kalo rulenya di jsid sih yang nambahin bukan kita sendiri, tapi orang lain yang kenal yang tau capability dan kontribusinya terhadap komunitas.
